[target.x86_64-pc-windows-msvc]
linker = "C:\\Program Files\\Microsoft Visual Studio\\18\\Community\\VC\\Tools\\MSVC\\14.51.36231\\bin\\Hostx64\\x64\\link.exe"
rustflags = [
    "-L", "C:\\Program Files\\Microsoft Visual Studio\\18\\Community\\VC\\Tools\\MSVC\\14.51.36231\\lib\\onecore\\x64",
    "-L", "C:\\Program Files\\Microsoft Visual Studio\\18\\Community\\SDK\\ScopeCppSDK\\vc15\\SDK\\lib",
]
